[project]
name = "llm-training"
version = "0.1.0"
description = "LLM training project (WSL2 + CUDA)"
requires-python = ">=3.11,<3.12"

dependencies = [
    "torch",
    "torchvision",
    "torchinfo",
    "transformers>=4.38.2",
    "datasets==2.18.0",
    "tiktoken",
    "numpy",
    "matplotlib",
    "requests",
    "scikit-learn==1.8.0",
    "psutil==5.9.8",
    "protobuf==4.25.3",
    "tqdm==4.66.2",
    "peft==0.10.0"
]

#torch==2.2.2+cu121
#torchvision==0.17.2+cu121
#torchaudio==2.2.2+cu121
#
#transformers==4.38.2
#datasets==2.18.0
#peft==0.10.0
#accelerate==0.28.0
#bitsandbytes==0.43.1
#
#numpy==1.26.4
#scipy==1.12.0
#sentencepiece==0.2.0
#protobuf==4.25.3
#tqdm==4.66.2


[dependency-groups]
dev = [
    "ipykernel",
]

#[tool.uv.sources]
#torch = { index = "pytorch-cuda" }
#torchvision = { index = "pytorch-cuda" }
#
#[[tool.uv.index]]
#name = "pytorch-cuda"
#url = "https://download.pytorch.org/whl/cu121"